MERCHANT_TO_CATEGORIES = {
    "ryanair": ["travel", "aviation", "fuel_costs"],
    "easyjet": ["travel", "aviation", "fuel_costs"],
    "wizz air": ["travel", "aviation"],
    "booking.com": ["travel", "hospitality"],
    "airbnb": ["travel", "hospitality"],
    "vueling": ["travel", "aviation"],
    "iberia": ["travel", "aviation"],
    "renfe": ["travel"],
    "amazon": ["ecommerce", "tech_stocks", "cloud"],
    "amazon prime": ["ecommerce", "tech_stocks", "streaming"],
    "mercadona": ["grocery", "consumer_staples"],
    "lidl": ["grocery", "consumer_staples"],
    "carrefour": ["grocery", "consumer_staples"],
    "aldi": ["grocery", "consumer_staples"],
    "inditex": ["retail", "consumer_discretionary"],
    "zara": ["retail", "consumer_discretionary"],
    "h&m": ["retail", "consumer_discretionary"],
    "netflix": ["streaming", "entertainment", "tech_stocks"],
    "spotify": ["streaming", "entertainment", "tech_stocks"],
    "disney+": ["streaming", "entertainment"],
    "hbo": ["streaming", "entertainment"],
    "apple store": ["tech_stocks", "consumer_electronics"],
    "apple": ["tech_stocks", "consumer_electronics"],
    "samsung": ["tech_stocks", "consumer_electronics"],
    "uber": ["transport", "ridesharing", "tech_stocks"],
    "cabify": ["transport", "ridesharing"],
    "bolt": ["transport", "ridesharing"],
    "iberdrola": ["energy", "renewables", "utilities"],
    "endesa": ["energy", "utilities"],
    "naturgy": ["energy", "utilities"],
    "enedis": ["energy", "utilities"],
    "trade republic": ["investing", "stocks", "etf"],
    "degiro": ["investing", "stocks", "etf"],
    "etoro": ["investing", "crypto", "stocks"],
    "coinbase": ["crypto", "investing"],
    "binance": ["crypto", "investing"],
    "microsoft": ["tech_stocks", "cloud", "enterprise_software"],
    "google": ["tech_stocks", "advertising", "cloud"],
    "meta": ["tech_stocks", "advertising", "social_media"],
    "paypal": ["fintech", "payments"],
    "revolut": ["fintech", "neobanking"],
    "n26": ["fintech", "neobanking"],
    "glovo": ["food_delivery", "consumer_discretionary"],
    "just eat": ["food_delivery", "consumer_discretionary"],
    "deliveroo": ["food_delivery", "consumer_discretionary"],
}

MERCHANT_TO_TICKERS = {
    "ryanair": ["RYAAY"],
    "easyjet": ["EZJ.L"],
    "amazon": ["AMZN"],
    "netflix": ["NFLX"],
    "spotify": ["SPOT"],
    "apple store": ["AAPL"],
    "apple": ["AAPL"],
    "uber": ["UBER"],
    "microsoft": ["MSFT"],
    "iberdrola": ["IBE.MC"],
    "mercadona": ["XLP"],
    "lidl": ["XLP"],
    "trade republic": ["GS", "MS"],
    "degiro": ["GS", "MS"],
}

CATEGORY_TO_TICKERS = {
    "travel": ["RYAAY", "JETS"],
    "aviation": ["RYAAY", "JETS"],
    "grocery": ["XLP"],
    "consumer_staples": ["XLP"],
    "tech_stocks": ["QQQ", "NVDA", "MSFT"],
    "crypto": ["BTC-USD", "ETH-USD"],
    "energy": ["IBE.MC", "ENPH"],
    "renewables": ["ICLN", "ENPH"],
    "ecommerce": ["AMZN"],
    "cloud": ["AMZN", "MSFT", "GOOGL"],
    "streaming": ["NFLX", "SPOT"],
    "investing": ["SPY", "QQQ"],
    "etf": ["SPY", "QQQ", "IWDA"],
    "macro": ["SPY", "GLD", "TLT"],
}


def get_categories(merchant: str) -> list[str]:
    return MERCHANT_TO_CATEGORIES.get(merchant.lower(), ["other"])


def get_tickers(merchant: str) -> list[str]:
    return MERCHANT_TO_TICKERS.get(merchant.lower(), [])
